networks:
  dev:

services:

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    networks:
      - dev

  backend:
    image: ghcr.io/edweiss200/mocky-backend:latest
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd src && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:12345@db:5432/mockybd
    depends_on:
      - db
      - redis
      - celery_worker
    networks:
      - dev

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=mockybd
    networks:
      - dev

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - dev

  celery_worker:
    image: ghcr.io/edweiss200/mocky-backend:latest
    working_dir: /app/src
    command: celery -A utils.worker.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    networks:
      - dev

  celery_beat:
    image: ghcr.io/edweiss200/mocky-backend:latest
    working_dir: /app/src
    command: celery -A utils.worker.celery beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    networks:
      - dev

  flower:
    image: ghcr.io/edweiss200/mocky-backend:latest
    working_dir: /app/src
    command: celery -A utils.worker.celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - dev

  tg-bot:
    image: ghcr.io/edweiss200/mocky-tg-bot:latest
    command: python main.py
    volumes:
      - ./app:/app
    depends_on:
      - backend
    env_file:
      - ./app/.env
    networks:
      - dev 
      
volumes:
  postgres_data:
  caddy_data:
  caddy_config: