"""empty message

Revision ID: 2b41b234e26d
Revises: ed29f6030838
Create Date: 2026-04-09 20:49:54.804944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b41b234e26d'
down_revision: Union[str, None] = 'ed29f6030838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('vacancy_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'vacancy_context')
    # ### end Alembic commands ###
