"""empty message

Revision ID: 5dd82bb48e14
Revises: fb4c9e27788c
Create Date: 2026-04-10 21:04:04.196729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd82bb48e14'
down_revision: Union[str, None] = 'fb4c9e27788c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('number_question', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'number_question')
    # ### end Alembic commands ###
