"""empty message

Revision ID: 657809bff39d
Revises: f6fa5b47f7bb
Create Date: 2026-04-25 19:35:42.718081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657809bff39d'
down_revision: Union[str, None] = 'f6fa5b47f7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interviews_user_id_fkey'), 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_interview_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_interview_id_fkey'), 'messages', 'interviews', ['interview_id'], ['id'])
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key(op.f('interviews_user_id_fkey'), 'interviews', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
