"""empty message

Revision ID: 8a5e29bf2368
Revises: 218e87ad0a0b
Create Date: 2026-04-17 14:39:05.012522

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8a5e29bf2368'
down_revision: Union[str, None] = '218e87ad0a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interviews_resume_id_fkey'), 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key(op.f('interviews_resume_id_fkey'), 'interviews', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###
