"""empty message

Revision ID: 99fd12a15de4
Revises: 2b41b234e26d
Create Date: 2026-04-09 21:15:03.165559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99fd12a15de4'
down_revision: Union[str, None] = '2b41b234e26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('prep_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'prep_plan')
    # ### end Alembic commands ###
