"""empty message

Revision ID: f6fa5b47f7bb
Revises: 8a5e29bf2368
Create Date: 2026-04-19 18:48:22.101161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fa5b47f7bb'
down_revision: Union[str, None] = '8a5e29bf2368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Integer(),server_default='0', nullable=False))
    op.add_column('users', sa.Column('subscription_tier', sa.String(), server_default='free', nullable=False))
    op.add_column('users', sa.Column('subscription_expiries_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('sprint_voice_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sprint_voice_used')
    op.drop_column('users', 'subscription_expiries_at')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
