"""empty message

Revision ID: fb4c9e27788c
Revises: 99fd12a15de4
Create Date: 2026-04-09 21:52:54.587305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4c9e27788c'
down_revision: Union[str, None] = '99fd12a15de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('role', sa.String(), server_default='pragmatic_lead', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'role')
    # ### end Alembic commands ###
